# Generated by Django 5.1.7 on 2025-03-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ROS_App", "0002_rename_review_text_review_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                default="images/dracula.jpg", upload_to="books/covers/"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(default="No description available."),
            preserve_default=False,
        ),
    ]
